spring:
    jpa:
        show_sql: true
        generate-ddl: true
oauth:
    key: protodirect-29893
    secret: vkdArhu2IJsL

event:
    baseUrl: https://www.appdirect.com/api/integration/v1/events/
